### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by cooperlees** [tox-dev/filelock#83]
Would this project be open to adding [static type annotations](https://mypy.readthedocs.io/en/stable/getting_started.html)? I ask as firelock is a dependency of mine and failing, naturally. 

We can either add the annotations directly to the source code (would require moving to py3 only or using Python 2 comment types - the latter adding tech debt) or we can go the route of adding a [.pyi stub](https://mypy.readthedocs.io/en/stable/stubs.html) file.

Is there any interest in this and if so, which approach would be preferred?

**Comment by cooperlees** [comment]
O, my bad, there are stubs already. But they seem to be failing for me. Have others got these working with mypy?

```
crl-m1:bandersnatch cooper$ /tmp/tb/bin/pip install types-filelock
Requirement already satisfied: types-filelock in /private/tmp/tb/lib/python3.9/site-packages (0.1.4)
```
And I get:
```
src/bandersnatch_storage_plugins/filesystem.py:12: note: Hint: "python3 -m pip install types-filelock"
src/bandersnatch/mirror.py:17: error: Library stubs not installed for
"filelock" (or incompatible with Python 3.8)
```

I'd still be open to directly typing the library if people are keen or it.

**Comment by cooperlees** [comment]
My bad - It was `pre-commit` virtualenv issues.

Added the following to mypy for other pre-commit peoples:
```
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        exclude: (docs/.*)
        additional_dependencies: ["types-filelock", "types-freezegun", "types-pkg_resources"]
```
